In [1]:
from visual import *

floor = box (pos=(0,0,0), length=4, height=0.5, width=4, color=color.blue)
ball = sphere (pos=(0,4,0), radius=1, color=color.red)
ball.velocity = vector(0,-1,0)
dt = 0.01

while 1:
    rate (100)
    ball.pos = ball.pos + ball.velocity*dt
    if ball.y < ball.radius:
        ball.velocity.y = abs(ball.velocity.y)
    else:
        ball.velocity.y = ball.velocity.y - 9.8*dt

ModuleNotFoundError: No module named 'visual'

In [1]:
import numpy as np
import math as mt
class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        print(self.input.shape[0])
        self.weights1   = np.random.rand(self.input.shape[0],4)
        print('weights 1',self.weights1)
        self.weights2   = np.random.rand(4,1)
        print('weights 2',self.weights2)
        self.y          = y
        self.output     = np.zeros(self.y.shape)

    def feedforward(self):
        #print(np.dot(self.input,self.weights1))        
        self.layer1 = self.sigmoid(np.dot(self.weights1.T, self.input))
        #print(np.dot(self.layer1,self.weights2))
        self.output = self.sigmoid(np.dot(self.weights2.T, self.layer1))
        print(self.output)
        
    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        print(self.sigmoid_derivative(self.output).shape)
        print(self.output.shape)
        print(self.y.shape)
        print(self.layer1.T.shape)
        d_weights2 = np.dot(self.layer1, (2*(self.y - self.output) * self.sigmoid_derivative(self.output)).T)
        print(self.weights2)
        print(d_weights2)
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * self.sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2
 
    def calcloss(self):
        self.loss = np.sum((self.y-self.output)*(self.y-self.output))
        
    def sigmoid(self,x):
        y = np.zeros(x.shape)
        for i in range(0,y.shape[0]):
            for j in range(0,y.shape[1]):
                y[i,j] = mt.exp(x[i,j])/(1 + mt.exp(x[i,j]))
        return y
    
    def sigmoid_derivative(self,x):
        y   = np.zeros(x.shape)
        sig = self.sigmoid(x)
        y   = sig*(1 - sig)
        return y
    

In [2]:
import math as mt
def sigmoid(x):
    y = mt.exp(x)/(1 + mt.exp(x))
    return y
x = -100  
y = np.array([-500,0,100])
z = np.array([1,1,1])
print(np.dot(y,z))
print(sigmoid(x))


-400
3.720075976020836e-44


In [3]:
x = np.array([[1,1,0,0],[1,0,1,0],[0,0,1,1]])
print(x)
y = np.array([0,1,0,1])
#x = [1,1,0,0]
#y = [1,0,1,0]
#x = 1
#y = 0
NN = NeuralNetwork(x,y)

[[1 1 0 0]
 [1 0 1 0]
 [0 0 1 1]]
3
weights 1 [[0.23094883 0.85215415 0.22680963 0.20977209]
 [0.44945767 0.36855933 0.38810629 0.57317494]
 [0.76934944 0.9316584  0.08559304 0.13631613]]
weights 2 [[0.59997099]
 [0.51073116]
 [0.43824163]
 [0.35406086]]


In [4]:
print(NN.feedforward())

[[0.78919874 0.75618937 0.79767924 0.76745271]]
None


In [5]:
print(NN.calcloss())

None


In [6]:
print(NN.loss)

1.372648686019818


In [7]:
print(np.sum((NN.output-NN.y)*(NN.output-NN.y)))

1.372648686019818


In [8]:
NN.backprop()

(1, 4)
(1, 4)
(4,)
(4, 4)
[[0.59997099]
 [0.51073116]
 [0.43824163]
 [0.35406086]]
[[-0.36076519]
 [-0.38364476]
 [-0.31903491]
 [-0.34929219]]


ValueError: shapes (1,4) and (1,4) not aligned: 4 (dim 1) != 1 (dim 0)